CREATE TABLE CLUB (CLUB_NAME VARCHAR(20) CONSTRAINT CLUB_NAME_NN NOT NULL,
                    CONVENER VARCHAR(20) CONSTRAINT CLUB_CONVENER_NN NOT NULL,
                    S_MEDIA VARCHAR(20),
                    CLUB_DESCRIPTION VARCHAR(50) CONSTRAINT CLUB_DESCRIPTION_NN NOT NULL,
                    CONSTRAINT CLUB_NAME_PK PRIMARY KEY(CLUB_NAME)
                    );
/
CREATE TABLE CO_CONVENER(CO_NAME VARCHAR(100),
                            C_NAME VARCHAR(20),
                            CONSTRAINT CO_CONVENER_NAME_FK FOREIGN KEY(C_NAME) REFERENCES CLUB(CLUB_NAME),
                            CONSTRAINT CO_CONV_CO_NAME_PK PRIMARY KEY(CO_NAME,C_NAME)
                            );
/
CREATE TABLE RECRUITMENT(C_NAME VARCHAR(20),
                        R_DATE TIMESTAMP,
                        VENUE VARCHAR(30) CONSTRAINT RECRUITMENT_VENUE_NN NOT NULL,
                        CONSTRAINT RECRUITMENT_PK PRIMARY KEY(C_NAME,R_DATE),
                        CONSTRAINT RECRUITMENT_CNAME_FK FOREIGN KEY(C_NAME) REFERENCES CLUB(CLUB_NAME)
                        );
/
CREATE TABLE MEETING(C_NAME VARCHAR(20),
                    M_DATE TIMESTAMP,
                    VENUE VARCHAR(30) CONSTRAINT MEETING_VENUE_NN NOT NULL,
                    DESCRIPTION VARCHAR(50) CONSTRAINT MEETING_DESC_NN NOT NULL,
                    CONSTRAINT MEETING_PK PRIMARY KEY(C_NAME,M_DATE),
                    CONSTRAINT MEETING_CNAME_FK FOREIGN KEY(C_NAME) REFERENCES CLUB(CLUB_NAME)
                    );
/
CREATE TABLE EVENT(E_ID NUMBER,
                    E_NAME VARCHAR(20) CONSTRAINT EVENT_NAME_NN NOT NULL,
                    E_DATE TIMESTAMP,
                    VENUE VARCHAR(30) CONSTRAINT EVENT_VENUE_NN NOT NULL,
                    DESCRIPTION VARCHAR(50) CONSTRAINT EVENT_DESC_NN NOT NULL,
                    C_NAME VARCHAR(20),
                    CONSTRAINT EVENT_PK PRIMARY KEY(E_ID,E_DATE),
                    CONSTRAINT EVENT_C_NAME_FK FOREIGN KEY(C_NAME) REFERENCES CLUB(CLUB_NAME)
                    );
/
CREATE SEQUENCE EVENT_SEQ
    START WITH 1
    NOMAXVALUE
    NOCYCLE
    ORDER;
/
CREATE INDEX RECRUITMENT_IDX ON RECRUITMENT(R_DATE);
CREATE INDEX MEETING_IDX ON MEETING(M_DATE);
CREATE INDEX EVENT_IDX ON EVENT(E_DATE);
/
-- DROP TABLE MEETING;
-- DROP TABLE CO_CONVENER;
/
CREATE TABLE AUDIT_TRAIL_CLUB(ACTION VARCHAR(10) CONSTRAINT AT_CLUB_ACTION_NN NOT NULL,
                                DATE_TIME TIMESTAMP CONSTRAINT AT_CLUB_DATE_TIME_NN NOT NULL,
                                CLUB_NAME VARCHAR(20),
                                CONVENER VARCHAR(20),
                                S_MEDIA VARCHAR(20),
                                CLUB_DESCRIPTION VARCHAR(50)
                                );
/
CREATE TABLE AUDIT_TRAIL_CO_CONVENER(ACTION VARCHAR(10) CONSTRAINT AT_CC_ACTION_NN NOT NULL,
                                DATE_TIME TIMESTAMP CONSTRAINT AT_CC_DATE_TIME_NN NOT NULL,
                                CO_NAME VARCHAR(20),
                                C_NAME VARCHAR(20)
                                );
/
CREATE TABLE AUDIT_TRAIL_RECRUITMENT(ACTION VARCHAR(10) CONSTRAINT AT_RECRUIT_ACTION_NN NOT NULL,
                                DATE_TIME TIMESTAMP CONSTRAINT AT_RECRUIT_DATE_TIME_NN NOT NULL,
                                C_NAME VARCHAR(20),
                                R_DATE TIMESTAMP,
                                VENUE VARCHAR(30)
                                );
/
CREATE TABLE AUDIT_TRAIL_MEETING(ACTION VARCHAR(10) CONSTRAINT AT_MEETING_ACTION_NN NOT NULL,
                                DATE_TIME TIMESTAMP CONSTRAINT AT_MEETING_DATE_TIME_NN NOT NULL,
                                C_NAME VARCHAR(20),
                                M_DATE TIMESTAMP,
                                VENUE VARCHAR(30)
                                );
/
CREATE TABLE AUDIT_TRAIL_EVENT(ACTION VARCHAR(10) CONSTRAINT AT_EVENT_ACTION_NN NOT NULL,
                                DATE_TIME TIMESTAMP CONSTRAINT AT_EVENT_DATE_TIME_NN NOT NULL,
                                E_ID NUMBER,
                                E_NAME VARCHAR(20),
                                E_DATE TIMESTAMP,
                                VENUE VARCHAR(30),
                                DESCRIPTION VARCHAR(50),
                                C_NAME VARCHAR(20)
                                );
/
CREATE OR REPLACE TRIGGER CLUB_CAP
    BEFORE
    INSERT OR UPDATE OF CLUB_NAME ON CLUB
    FOR EACH ROW
    BEGIN
    :NEW.CLUB_NAME := INITCAP(:NEW.CLUB_NAME);
END CLUB_CAP;
/
CREATE OR REPLACE TRIGGER TRAIL_CLUB
    AFTER
    INSERT OR UPDATE OR DELETE ON CLUB
    FOR EACH ROW
    DECLARE
        ACT AUDIT_TRAIL_CLUB.ACTION%TYPE;
    BEGIN
        IF INSERTING THEN ACT := 'INSERT';
        ELSIF UPDATING THEN ACT:='UPDATE';
        ELSE ACT:= 'DELETE';
        END IF;
        INSERT INTO AUDIT_TRAIL_CLUB VALUES(ACT,
                                SYSTIMESTAMP,
                                :OLD.CLUB_NAME,
                                :OLD.CONVENER,
                                :OLD.S_MEDIA,
                                :OLD.CLUB_DESCRIPTION);
END TRAIL_CLUB;
/
CREATE OR REPLACE TRIGGER TRAIL_CO_CONV
    AFTER
    INSERT OR UPDATE OR DELETE ON CO_CONVENER
    FOR EACH ROW
    DECLARE
        ACT AUDIT_TRAIL_CO_CONVENER.ACTION%TYPE;
    BEGIN
        IF INSERTING THEN ACT := 'INSERT';
        ELSIF UPDATING THEN ACT:='UPDATE';
        ELSE ACT:= 'DELETE';
        END IF;
        INSERT INTO AUDIT_TRAIL_CO_CONVENER VALUES(ACT,
                                SYSTIMESTAMP,
                                :OLD.C_NAME,
                                :OLD.CO_NAME);
END TRAIL_CO_CONV;
/
CREATE OR REPLACE TRIGGER TRAIL_RECRUITMENT 
    AFTER
    INSERT OR UPDATE OR DELETE ON RECRUITMENT
    FOR EACH ROW
    DECLARE
        ACT AUDIT_TRAIL_RECRUITMENT.ACTION%TYPE;
    BEGIN
        IF INSERTING THEN ACT := 'INSERT';
        ELSIF UPDATING THEN ACT:='UPDATE';
        ELSE ACT:= 'DELETE';
        END IF;
        INSERT INTO AUDIT_TRAIL_RECRUITMENT VALUES(ACT,
                                SYSTIMESTAMP,
                                :OLD.C_NAME,
                                :OLD.R_DATE,
                                :OLD.VENUE);
END TRAIL_RECRUITMENT;
/
CREATE OR REPLACE TRIGGER TRAIL_MEETING 
    AFTER
    INSERT OR UPDATE OR DELETE ON MEETING
    FOR EACH ROW
    DECLARE
        ACT AUDIT_TRAIL_MEETING.ACTION%TYPE;
    BEGIN
        IF INSERTING THEN ACT := 'INSERT';
        ELSIF UPDATING THEN ACT:='UPDATE';
        ELSE ACT:= 'DELETE';
        END IF;
        INSERT INTO AUDIT_TRAIL_MEETING VALUES(ACT,
                                SYSTIMESTAMP,
                                :OLD.C_NAME,
                                :OLD.M_DATE,
                                :OLD.VENUE);
END TRAIL_MEETING;
/
CREATE OR REPLACE TRIGGER TRAIL_EVENT
    AFTER
    INSERT OR UPDATE OR DELETE ON EVENT
    FOR EACH ROW
    DECLARE
        ACT AUDIT_TRAIL_EVENT.ACTION%TYPE;
    BEGIN
        IF INSERTING THEN ACT := 'INSERT';
        ELSIF UPDATING THEN ACT:='UPDATE';
        ELSE ACT:= 'DELETE';
        END IF;
        INSERT INTO AUDIT_TRAIL_EVENT VALUES(ACT,
                                SYSTIMESTAMP,
                                :OLD.E_ID,
                                :OLD.E_NAME,
                                :OLD.E_DATE,
                                :OLD.VENUE,
                                :OLD.DESCRIPTION,
                                :OLD.C_NAME);
END TRAIL_EVENT;

/
CREATE OR REPLACE PACKAGE CLUB_PACK AS
TYPE CLUB_VIEW_ARRAY IS VARRAY(10) OF CLUB_VIEW%ROWTYPE;
PROCEDURE INSERT_CLUB(CLUB_NAME IN VARCHAR,CONVENER IN VARCHAR,S_MEDIA IN VARCHAR,CLUB_DESCRIPTION IN VARCHAR);
PROCEDURE INSERT_CO_CONVENER(CO_NAME VARCHAR,C_NAME VARCHAR)  ;
PROCEDURE INSERT_RECRUITMENT(C_NAME VARCHAR,R_DATE TIMESTAMP,VENUE VARCHAR)  ;
PROCEDURE INSERT_MEETING(C_NAME VARCHAR,M_DATE TIMESTAMP,VENUE VARCHAR,DESCRIPTION VARCHAR)  ;
PROCEDURE INSERT_EVENT(E_NAME VARCHAR,E_DATE TIMESTAMP,VENUE VARCHAR,DESCRIPTION VARCHAR,C_NAME VARCHAR)  ;
PROCEDURE UPDATE_CLUB(CLUB_N VARCHAR,CONV VARCHAR,S_M VARCHAR,CLUB_DESC VARCHAR)  ;
PROCEDURE UPDATE_CO_CONVENER(CO_N VARCHAR,C_N VARCHAR)  ;
PROCEDURE UPDATE_RECRUITMENT(C_N VARCHAR,R_D TIMESTAMP,VEN VARCHAR)  ;
PROCEDURE UPDATE_MEETING(C_N VARCHAR,M_D TIMESTAMP,VEN VARCHAR,DESCR VARCHAR)  ;
PROCEDURE UPDATE_EVENT(E_I NUMBER,E_N VARCHAR,E_D TIMESTAMP,VEN VARCHAR,DESCR VARCHAR,C_N VARCHAR)  ;
PROCEDURE DELETE_CLUB(CLUB_N VARCHAR)  ;
PROCEDURE DELETE_CO_CONVENER(CO_N VARCHAR,C_N VARCHAR)  ;
PROCEDURE DELETE_RECRUITMENT(C_N VARCHAR,R_D TIMESTAMP)  ;
PROCEDURE DELETE_MEETING(C_N VARCHAR,M_D TIMESTAMP)  ;
PROCEDURE DELETE_EVENT(E_I NUMBER,E_D TIMESTAMP)  ;
FUNCTION GET_CLUB(CLUB_N VARCHAR) RETURN CLUB_VIEW%ROWTYPE;
FUNCTION GET_CLUBS RETURN CLUB_VIEW_ARRAY;
END CLUB_PACK;
/
CREATE OR REPLACE PACKAGE BODY CLUB_PACK AS
PROCEDURE INSERT_CLUB(CLUB_NAME VARCHAR,CONVENER VARCHAR,S_MEDIA VARCHAR,CLUB_DESCRIPTION VARCHAR)
AS
    BEGIN
    INSERT INTO CLUB VALUES(CLUB_NAME,CONVENER,S_MEDIA,CLUB_DESCRIPTION);
END INSERT_CLUB;
PROCEDURE INSERT_CO_CONVENER(CO_NAME VARCHAR,C_NAME VARCHAR)
AS
    BEGIN
    INSERT INTO CO_CONVENER VALUES(CO_NAME,C_NAME);
END INSERT_CO_CONVENER;
PROCEDURE INSERT_RECRUITMENT(C_NAME VARCHAR,R_DATE TIMESTAMP,VENUE VARCHAR)  
AS
    BEGIN
    INSERT INTO RECRUITMENT VALUES(C_NAME,R_DATE,VENUE);
END INSERT_RECRUITMENT;
PROCEDURE INSERT_MEETING(C_NAME VARCHAR,M_DATE TIMESTAMP,VENUE VARCHAR,DESCRIPTION VARCHAR)  
AS
    BEGIN
    INSERT INTO MEETING VALUES(C_NAME,M_DATE,VENUE,DESCRIPTION);
END INSERT_MEETING;
PROCEDURE INSERT_EVENT(E_NAME VARCHAR,E_DATE TIMESTAMP,VENUE VARCHAR,DESCRIPTION VARCHAR,C_NAME VARCHAR)  
AS
    BEGIN
    INSERT INTO EVENT VALUES(EVENT_SEQ.NEXTVAL,E_NAME,E_DATE,VENUE,DESCRIPTION,C_NAME);
END INSERT_EVENT;
PROCEDURE UPDATE_CLUB(CLUB_N VARCHAR,CONV VARCHAR,S_M VARCHAR,CLUB_DESC VARCHAR)  
AS
    BEGIN
    UPDATE CLUB
        SET CLUB.CLUB_NAME = CLUB_N,CLUB.CONVENER = CONV,CLUB.S_MEDIA = S_M,CLUB.CLUB_DESCRIPTION = CLUB_DESC
        WHERE CLUB.CLUB_NAME = CLUB_N;
END UPDATE_CLUB;
PROCEDURE UPDATE_CO_CONVENER(CO_N VARCHAR,C_N VARCHAR)  
AS
    BEGIN
    UPDATE CO_CONVENER
        SET CO_CONVENER.CO_NAME = CO_N,CO_CONVENER.C_NAME = C_N
        WHERE CO_CONVENER.CO_NAME = CO_N AND CO_CONVENER.C_NAME = C_N;
END UPDATE_CO_CONVENER;
PROCEDURE UPDATE_RECRUITMENT(C_N VARCHAR,R_D TIMESTAMP,VEN VARCHAR)  
AS
    BEGIN
    UPDATE RECRUITMENT
        SET RECRUITMENT.C_NAME = C_N,RECRUITMENT.R_DATE = R_D,RECRUITMENT.VENUE = VEN
        WHERE RECRUITMENT.C_NAME = C_N AND RECRUITMENT.R_DATE = R_D;
END UPDATE_RECRUITMENT;
PROCEDURE UPDATE_MEETING(C_N VARCHAR,M_D TIMESTAMP,VEN VARCHAR,DESCR VARCHAR)  
AS
    BEGIN
    UPDATE MEETING
        SET MEETING.C_NAME = C_N,MEETING.M_DATE = M_D,MEETING.VENUE = VEN,MEETING.DESCRIPTION = DESCR
        WHERE MEETING.C_NAME = C_N AND MEETING.M_DATE = M_D;
END UPDATE_MEETING;
PROCEDURE UPDATE_EVENT(E_I NUMBER,E_N VARCHAR,E_D TIMESTAMP,VEN VARCHAR,DESCR VARCHAR,C_N VARCHAR)  
AS
    BEGIN
    UPDATE EVENT
        SET EVENT.E_NAME = E_N,EVENT.E_DATE = E_D,EVENT.VENUE = VEN,EVENT.DESCRIPTION = DESCR,EVENT.C_NAME = C_N
        WHERE EVENT.E_ID = E_I AND EVENT.E_DATE =E_D;
END UPDATE_EVENT;
PROCEDURE DELETE_CLUB(CLUB_N VARCHAR)  
AS
    BEGIN
    DELETE FROM CLUB WHERE CLUB.CLUB_NAME = CLUB_N;
    DELETE FROM CO_CONVENER WHERE CO_CONVENER.C_NAME = CLUB_N;
     
     
END DELETE_CLUB;
PROCEDURE DELETE_CO_CONVENER(CO_N VARCHAR,C_N VARCHAR)  
AS
    BEGIN
    DELETE FROM CO_CONVENER WHERE CO_CONVENER.CO_NAME = CO_N AND CO_CONVENER.C_NAME = C_N;
     
     
END DELETE_CO_CONVENER;
PROCEDURE DELETE_RECRUITMENT(C_N VARCHAR,R_D TIMESTAMP)  
AS
    BEGIN
    DELETE FROM RECRUITMENT WHERE RECRUITMENT.C_NAME = C_N AND RECRUITMENT.R_DATE = R_D;
     
     
END DELETE_RECRUITMENT;
PROCEDURE DELETE_MEETING(C_N VARCHAR,M_D TIMESTAMP)  
AS
    BEGIN
    DELETE FROM MEETING WHERE MEETING.C_NAME = C_N AND MEETING.M_DATE = M_D;
     
     
END DELETE_MEETING;
PROCEDURE DELETE_EVENT(E_I NUMBER,E_D TIMESTAMP)  
AS
    BEGIN
    DELETE FROM EVENT WHERE EVENT.E_ID = E_I AND EVENT.E_DATE = E_D;
     
     
END DELETE_EVENT;
FUNCTION GET_CLUB(CLUB_N VARCHAR) RETURN CLUB_VIEW%ROWTYPE
AS
    CURSOR CUR IS SELECT * FROM CLUB_VIEW WHERE CLUB_VIEW.CLUB_NAME = CLUB_N;
    RES CUR%ROWTYPE;
    NAME_OF_CONV VARCHAR(100):=' ';
    BEGIN
    OPEN CUR;
    LOOP
        EXIT WHEN CUR%NOTFOUND;
        FETCH CUR INTO RES;
        EXIT WHEN CUR%NOTFOUND;
        EXIT WHEN RES.CO_NAME = '' OR RES.CO_NAME = NULL;
        NAME_OF_CONV:=RES.CO_NAME || ' , ' ||NAME_OF_CONV;
    END LOOP;
    -- SELECT * INTO HOLDER FROM CLUB_VIEW FETCH FIRST 1 ROW ONLY;
    RES.CO_NAME := RTRIM(NAME_OF_CONV,' ,');
    CLOSE CUR;
    RETURN RES;
END GET_CLUB;
FUNCTION GET_CLUBS RETURN CLUB_VIEW_ARRAY
AS
    HOLDER CLUB_VIEW_ARRAY := CLUB_VIEW_ARRAY();
    CURSOR CUR IS SELECT * FROM CLUB;
    RES CUR%ROWTYPE;
    I NUMBER := 1;
    IF_EXISTS NUMBER;
    INDIVIDUAL_HOLDER CLUB_VIEW%ROWTYPE;
    BEGIN
    OPEN CUR;
    LOOP
        EXIT WHEN CUR%NOTFOUND;
        FETCH CUR INTO RES;
        EXIT WHEN CUR%NOTFOUND;
        HOLDER.EXTEND;
        SELECT COUNT(*) INTO IF_EXISTS FROM CLUB_VIEW WHERE CLUB_VIEW.CLUB_NAME = RES.CLUB_NAME;
        IF IF_EXISTS != 0 THEN
            HOLDER(I) := GET_CLUB(RES.CLUB_NAME);
        ELSE
            INDIVIDUAL_HOLDER.CLUB_NAME := RES.CLUB_NAME;
            INDIVIDUAL_HOLDER.CONVENER := RES.CONVENER;
            INDIVIDUAL_HOLDER.CO_NAME := '';
            INDIVIDUAL_HOLDER.S_MEDIA := RES.S_MEDIA;
            INDIVIDUAL_HOLDER.CLUB_DESCRIPTION := RES.CLUB_DESCRIPTION;
            HOLDER(I):= INDIVIDUAL_HOLDER;
        END IF;
            I := I + 1;
    END LOOP;
    CLOSE CUR;
    RETURN HOLDER;
END GET_CLUBS;
END CLUB_PACK;

-- DROP PACKAGE CLUB_PACK;
-- exec CLUB_PACK.INSERT_CLUB('CLUB','CONVENER','MEDIA','DESCRIPTION');
-- TRUNCATE TABLE CLUB;
-- exec DBMS_OUTPUT.PUT_LINE('meow')
-- INSERT INTO CO_CONVENER VALUES('Arshia','Magboard');

CREATE VIEW CLUB_VIEW AS
    SELECT CLUB_NAME,CONVENER,CO_NAME,S_MEDIA,CLUB_DESCRIPTION 
    FROM CLUB JOIN CO_CONVENER ON CLUB.CLUB_NAME = CO_CONVENER.C_NAME;


-- DROP VIEW CLUB_VIEW;
-- TRUNCATE TABLE CO_CONVENER;
-- DELETE FROM CO_CONVENER WHERE C_NAME = 'Name';
-- CREATE or REPLACE TYPE TEST_TYPE IS VARRAY(10) OF CLUB_VIEW%ROWTYPE;